// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models
{
    public partial class Country
    {
        public Country()
        {
            PopulationCounts = new HashSet<PopulationCount>();
        }

        [Key]
        public int CountryID { get; set; }
        [Required]
        [StringLength(150)]
        public string CountryName { get; set; }
        [StringLength(150)]
        public string code { get; set; }

        [InverseProperty("Country")]
        public virtual ICollection<PopulationCount> PopulationCounts { get; set; }
    }
}