// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models
{
    public partial class PopulationCount
    {
        [Key]
        public int id { get; set; }
        public int? year { get; set; }
        [StringLength(100)]
        public string value { get; set; }
        public int? CountryID { get; set; }

        [ForeignKey("CountryID")]
        [InverseProperty("PopulationCounts")]
        public virtual Country Country { get; set; }
    }
}